/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetofinalpoo;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author gusta
 */
public class NewJFrame4 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame4
     */
    public NewJFrame4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IMAGEM = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dialogo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        IMAGEM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetofinalpoo/por do sol binario.jpg"))); // NOI18N

        jButton1.setText("Lutar!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Correr!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        dialogo.setColumns(20);
        dialogo.setRows(5);
        jScrollPane1.setViewportView(dialogo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(151, 151, 151))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IMAGEM)
                        .addContainerGap(134, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(IMAGEM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private Aventura oneventure;

    public Aventura getOneventure() {
        return oneventure;
    }

    public void setOneventure(Aventura oneventure) {
        this.oneventure = oneventure;
        ImageIcon img = new ImageIcon(this.getClass().getResource("/projetofinalpoo/inicial.jpg"));
        IMAGEM.setIcon(img);
        dialogo.setLineWrap(true);
        dialogo.setText("Enquanto caminha pela masmorra, uma figura espreita \n pelas sombras e com seus inumeros olhos o pavor se forma em sua frente");
        if(oneventure.getX()==1){
        if(oneventure.player1.getHpAtual()<1){
        ImageIcon imge = new ImageIcon(this.getClass().getResource("/projetofinalpoo/morte.jpg"));
        IMAGEM.setIcon(imge);
         dialogo.setLineWrap(true);
        dialogo.setText("Pessoas mortas não contam ou fazem historia, seu personagem pereceu nessa masmorra!!");
        oneventure.monstroAtual.delete();
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        }}else if(oneventure.getX()==2){
        if(oneventure.player2.getHpAtual()<1){
        ImageIcon imge = new ImageIcon(this.getClass().getResource("/projetofinalpoo/morte.jpg"));
        IMAGEM.setIcon(imge);
        dialogo.setLineWrap(true);
        dialogo.setText("Pessoas mortas não contam ou fazem historia, seu personagem pereceu nessa masmorra!!");
        oneventure.monstroAtual.delete();
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        }} else if(oneventure.getX()==3){
        if(oneventure.player3.getHpAtual()<1){
        ImageIcon imge = new ImageIcon(this.getClass().getResource("/projetofinalpoo/morte.jpg"));
        IMAGEM.setIcon(imge);
        oneventure.monstroAtual.delete();
        dialogo.setLineWrap(true);
        dialogo.setText("Pessoas mortas não contam ou fazem historia, seu personagem pereceu nessa masmorra!!");
         jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        }}
    }
   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ImageIcon img = new ImageIcon(this.getClass().getResource("/projetofinalpoo/luta.jpg"));
        IMAGEM.setIcon(img);
         dialogo.setLineWrap(true);
        dialogo.setText("Você desesperadamente ataca o monstro buscando sua sobrevivencia,\n continue lutando, ou fuja!!");
        try {
            oneventure.atacar();
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame4.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(oneventure.getX()==1){
        if(oneventure.player1.getHpAtual()<= 0){
        ImageIcon imge = new ImageIcon(this.getClass().getResource("/projetofinalpoo/morte.jpg"));
        IMAGEM.setIcon(imge);
        oneventure.monstroAtual.delete();
        dialogo.setLineWrap(true);
        dialogo.setText("O/a bravo(a) guerreiro(a) "+oneventure.player1.getNome() +" pereceu na masmorra \n mas não fique triste, crie outro personagem e jogue novamente");
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        }}else if(oneventure.getX()==2){
        if(oneventure.player2.getHpAtual()<= 0){
        ImageIcon imge = new ImageIcon(this.getClass().getResource("/projetofinalpoo/morte.jpg"));
        IMAGEM.setIcon(imge);
        oneventure.monstroAtual.delete();
        dialogo.setLineWrap(true);
        dialogo.setText("O/a bravo(a) mago(a) "+oneventure.player2.getNome() +" pereceu na masmorra \n mas não fique triste, crie outro personagem e jogue novamente");
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        }} else if(oneventure.getX()==3){
        if(oneventure.player3.getHpAtual()<= 0){
        ImageIcon imge = new ImageIcon(this.getClass().getResource("/projetofinalpoo/morte.jpg"));
        IMAGEM.setIcon(imge);
        oneventure.monstroAtual.delete();
        dialogo.setLineWrap(true);
        dialogo.setText("O/a bravo(a) arqueiro(a) "+oneventure.player3.getNome() +" pereceu na masmorra \n mas não fique triste, crie outro personagem e jogue novamente");
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        }}
        if(oneventure.monstroAtual.getHp()<1){
        ImageIcon imge = new ImageIcon(this.getClass().getResource("/projetofinalpoo/victory.jpg"));
        IMAGEM.setIcon(imge);
        if(oneventure.getX()==1){
         dialogo.setLineWrap(true);
         dialogo.setText("O/a bravo(a) guerreiro(a) " +oneventure.player1.getNome() + " pós fim ao reinado \n de terror do observador e ganhou xp com isso");
        }else if(oneventure.getX()==2){
             dialogo.setLineWrap(true);
            dialogo.setText("O/a bravo(a) mago(a) " +oneventure.player2.getNome() + " pós fim ao reinado \n de terror do observador e ganhou xp com isso");
        }else if(oneventure.getX()==3){
             dialogo.setLineWrap(true);
            dialogo.setText("O/a bravo(a) arqueiro(a) " +oneventure.player3.getNome() + " pós fim ao reinado \n de terror do observador e ganhou xp com isso");
        }
        oneventure.monstroAtual.delete();
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         ImageIcon img = new ImageIcon(this.getClass().getResource("/projetofinalpoo/fuga.jpg"));
        IMAGEM.setIcon(img);
        dialogo.setText("você corre desesperado da criatura em direção a saida da masmorra");
        try {
            oneventure.correr();
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame4.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(oneventure.getX()==1){
        if(oneventure.player1.getHpAtual()<= 0){
        ImageIcon imge = new ImageIcon(this.getClass().getResource("/projetofinalpoo/morte.jpg"));
        IMAGEM.setIcon(imge);
        dialogo.setText("O/a bravo(a) guerreiro(a) "+oneventure.player1.getNome() +"  não coseguiu fugir e pereceu na masmorra \n mas não fique triste, crie outro personagem e jogue novamente");
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        }}else if(oneventure.getX()==2){
        if(oneventure.player2.getHpAtual()<= 0){
        ImageIcon imge = new ImageIcon(this.getClass().getResource("/projetofinalpoo/morte.jpg"));
        IMAGEM.setIcon(imge);
        dialogo.setText("O/a bravo(a) mago(a) "+oneventure.player2.getNome() +" não coseguiu fugir e pereceu na masmorra \n mas não fique triste, crie outro personagem e jogue novamente");
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        }} else if(oneventure.getX()==3){
        if(oneventure.player3.getHpAtual()<= 0){
        ImageIcon imge = new ImageIcon(this.getClass().getResource("/projetofinalpoo/morte.jpg"));
        IMAGEM.setIcon(imge);
        dialogo.setText("O/a bravo(a) arqueiro(a) "+oneventure.player3.getNome() +" não coseguiu fugir e pereceu na masmorra \n mas não fique triste, crie outro personagem e jogue novamente");
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        }}
        if(oneventure.monstroAtual.getD()>=12){
        ImageIcon imge = new ImageIcon(this.getClass().getResource("/projetofinalpoo/survivor.jpg"));
        IMAGEM.setIcon(imge);
        dialogo.setText("você conseguiu escapar da masmorra com vida, mas não pense que \n sera tão facil da proxima vez");
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
    }//GEN-LAST:event_jButton2ActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame4().setVisible(true);
            }
        });
    }
  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IMAGEM;
    private javax.swing.JTextArea dialogo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
