/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetofinalpoo;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author gusta
 */
public class NewJFrame3 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame3
     */
    public NewJFrame3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IMAGE = new javax.swing.JLabel();
        txtdestreza = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtconstituicao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtinteligencia = new javax.swing.JTextField();
        txtsabedoria = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtcarisma = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtnivel = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtxp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txthp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtdeslocamento = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        txtraca = new javax.swing.JTextField();
        txtclasse = new javax.swing.JTextField();
        txtidade = new javax.swing.JTextField();
        txtsexo = new javax.swing.JTextField();
        txtforca = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        IMAGE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetofinalpoo/por do sol binario.jpg"))); // NOI18N

        jLabel2.setText("PERSONAGEM:");

        jLabel3.setText("RAÇA");

        jLabel4.setText("CLASSE:");

        jLabel5.setText("IDADE:");

        jLabel6.setText("SEXO:");

        jLabel7.setText("FORÇA:");

        jLabel8.setText("DESTREZA:");

        jLabel9.setText("CONSTITUIÇÃO:");

        jLabel10.setText("INTELIGENCIA:");

        jLabel17.setText("DESLOCAMENTO:");

        jLabel11.setText("SABEDORIA:");

        jLabel12.setText("CARISMA:");

        jButton1.setText("JOGAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel13.setText("NIVEL:");

        jLabel14.setText("XP:");

        jButton2.setText("SAIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel15.setText("HP:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IMAGE, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jButton2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtsexo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtforca, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtdestreza))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtidade, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtinteligencia))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtconstituicao))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtclasse))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtraca, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtsabedoria))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtcarisma, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtxp, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnivel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txthp, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtdeslocamento, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(IMAGE, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtraca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtclasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtforca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtdestreza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtconstituicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtinteligencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtsabedoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtcarisma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtdeslocamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtxp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txthp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         NewJFrame form2 = new NewJFrame();  
            form2.setVisible(true);  
            dispose();
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      if(x==1){
          try {
              Aventura oneventura = new Aventura(player1);
               NewJFrame4 form1 = new NewJFrame4();
               form1.setOneventure(oneventura);
                form1.setVisible(true);  
                dispose();
          } catch (IOException ex) {
              Logger.getLogger(NewJFrame3.class.getName()).log(Level.SEVERE, null, ex);
          }
      }else if(x==2){
       try {
              Aventura oneventura = new Aventura(player2);
              NewJFrame4 form1 = new NewJFrame4();
               form1.setOneventure(oneventura);
                form1.setVisible(true);  
                dispose();
          } catch (IOException ex) {
              Logger.getLogger(NewJFrame3.class.getName()).log(Level.SEVERE, null, ex);
          }
      }else if(x==3){
       try {
              Aventura oneventura = new Aventura(player3);
              NewJFrame4 form1 = new NewJFrame4();
               form1.setOneventure(oneventura);
                form1.setVisible(true);  
                dispose();
          } catch (IOException ex) {
              Logger.getLogger(NewJFrame3.class.getName()).log(Level.SEVERE, null, ex);
          }
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame3().setVisible(true);
            }
        });
    }
    private Guerreiro player1;
    private Mago player2;
    private Arqueiro player3;
    private int x;

    public Guerreiro getPlayer1() {
        return player1;
    }

    public void setPlayer1(Guerreiro player1) {
        this.player1 = player1;
        txtnome.setText(player1.getNome());
        txtraca.setText(player1.getRaca());
        txtclasse.setText(player1.getClasse());
        txtidade.setText(Integer.toString(player1.getIdade()));
        txtsexo.setText(player1.getSexo());
        txtforca.setText(Integer.toString(player1.getForca()));
        txtdestreza.setText(Integer.toString(player1.getDestreza()));
        txtconstituicao.setText(Integer.toString(player1.getConstituicao()));
        txtinteligencia.setText(Integer.toString(player1.getInteligencia()));
        txtsabedoria.setText(Integer.toString(player1.getSabedoria()));
        txtcarisma.setText(Integer.toString(player1.getCarisma()));
        txtdeslocamento.setText(Integer.toString(player1.getDeslocamento()));
        txtnivel.setText(Integer.toString(player1.getNivel()));
        txtxp.setText(Integer.toString(player1.getXp())+"/" + Integer.toString(player1.getNivel()*300));
        txthp.setText(Integer.toString(player1.getHpAtual())+"/" + Integer.toString(player1.getHp()));
        if("M".equals(player1.getSexo())){
          if("Anão".equals(player1.getRaca())){
                  ImageIcon img = new ImageIcon(this.getClass().getResource("/projetofinalpoo/dwarf-M-guerreiro.jpg"));
                  IMAGE.setIcon(img);
          }else if("Elfo".equals(player1.getRaca())){
                  ImageIcon img = new ImageIcon(this.getClass().getResource("/projetofinalpoo/elf-M-guerreiro.jpg"));
                  IMAGE.setIcon(img); 
          }else if("Humano".equals(player1.getRaca())){
              ImageIcon img = new ImageIcon(this.getClass().getResource("/projetofinalpoo/human-M-guerreiro.jpg"));
                  IMAGE.setIcon(img);
          }else if("Orc".equals(player1.getRaca())){
              ImageIcon img = new ImageIcon(this.getClass().getResource("/projetofinalpoo/orc-M-guerreiro.jpg"));
                  IMAGE.setIcon(img);
          }else if("Tiefling".equals(player1.getRaca())){
                   ImageIcon img = new ImageIcon(this.getClass().getResource("/projetofinalpoo/tiefling-M-guerreiro.jpg"));
                  IMAGE.setIcon(img);
            }
        
        }else{
         if("Anão".equals(player1.getRaca())){
                  ImageIcon img = new ImageIcon(this.getClass().getResource("/projetofinalpoo/dwarf-F-guerreiro.jpg"));
                  IMAGE.setIcon(img);
          }else if("Elfo".equals(player1.getRaca())){
                  ImageIcon img = new ImageIcon(this.getClass().getResource("/projetofinalpoo/elf-F-guerreiro.jpg"));
                  IMAGE.setIcon(img); 
          }else if("Humano".equals(player1.getRaca())){
              ImageIcon img = new ImageIcon(this.getClass().getResource("/projetofinalpoo/human-F-guerreiro.jpg"));
                  IMAGE.setIcon(img);
          }else if("Orc".equals(player1.getRaca())){
              ImageIcon img = new ImageIcon(this.getClass().getResource("/projetofinalpoo/orc-F-guerreiro.jpg"));
                  IMAGE.setIcon(img);
          }else if("Tiefling".equals(player1.getRaca())){ 
                   ImageIcon img = new ImageIcon(this.getClass().getResource("/projetofinalpoo/tiefling-F-guerreiro.jpg"));
                  IMAGE.setIcon(img);
            }
        }
    }

    public Mago getPlayer2() {
        return player2;
    }

    public void setPlayer2(Mago player2) {
        this.player2 = player2;
        txtnome.setText(player2.getNome());
        txtraca.setText(player2.getRaca());
        txtclasse.setText(player2.getClasse());
        txtidade.setText(Integer.toString(player2.getIdade()));
        txtsexo.setText(player2.getSexo());
        txtforca.setText(Integer.toString(player2.getForca()));
        txtdestreza.setText(Integer.toString(player2.getDestreza()));
        txtconstituicao.setText(Integer.toString(player2.getConstituicao()));
        txtinteligencia.setText(Integer.toString(player2.getInteligencia()));
        txtsabedoria.setText(Integer.toString(player2.getSabedoria()));
        txtcarisma.setText(Integer.toString(player2.getCarisma()));
        txtdeslocamento.setText(Integer.toString(player2.getDeslocamento()));
        txtnivel.setText(Integer.toString(player2.getNivel()));
        txtxp.setText(Integer.toString(player2.getXp())+"/" + Integer.toString(player2.getNivel()*300));
        txthp.setText(Integer.toString(player2.getHpAtual())+"/" + Integer.toString(player2.getHp()));
       if("M".equals(player2.getSexo())){
          if("Anão".equals(player2.getRaca())){
                  ImageIcon img = new ImageIcon(this.getClass().getResource("/projetofinalpoo/dwarf-M-mago.jpg"));
                  IMAGE.setIcon(img);
          }else if("Elfo".equals(player2.getRaca())){
                  ImageIcon img = new ImageIcon(this.getClass().getResource("/projetofinalpoo/elf-M-mago.jpg"));
                  IMAGE.setIcon(img); 
          }else if("Humano".equals(player2.getRaca())){
              ImageIcon img = new ImageIcon(this.getClass().getResource("/projetofinalpoo/human-M-mago.jpg"));
                  IMAGE.setIcon(img);
          }else if("Orc".equals(player2.getRaca())){
              ImageIcon img = new ImageIcon(this.getClass().getResource("/projetofinalpoo/orc-M-mago.jpg"));
                  IMAGE.setIcon(img);
          }else if("Tiefling".equals(player2.getRaca())){
                   ImageIcon img = new ImageIcon(this.getClass().getResource("/projetofinalpoo/tiefling-M-mago.jpg"));
                  IMAGE.setIcon(img);
            }
        
        }else{
         if("Anão".equals(player2.getRaca())){
                  ImageIcon img = new ImageIcon(this.getClass().getResource("/projetofinalpoo/dwarf-F-mago.jpg"));
                  IMAGE.setIcon(img);
          }else if("Elfo".equals(player2.getRaca())){
                  ImageIcon img = new ImageIcon(this.getClass().getResource("/projetofinalpoo/elf-F-mago.jpg"));
                  IMAGE.setIcon(img); 
          }else if("Humano".equals(player2.getRaca())){
              ImageIcon img = new ImageIcon(this.getClass().getResource("/projetofinalpoo/human-F-mago.jpg"));
                  IMAGE.setIcon(img);
          }else if(player2.getRaca()== "Orc"){
              ImageIcon img = new ImageIcon(this.getClass().getResource("/projetofinalpoo/orc-F-mago.jpg"));
                  IMAGE.setIcon(img);
          }else if("Tiefling".equals(player2.getRaca())){
                   ImageIcon img = new ImageIcon(this.getClass().getResource("/projetofinalpoo/tiefling-F-mago.jpg"));
                  IMAGE.setIcon(img);
            }
        }
        
    }

    public Arqueiro getPlayer3() {
        return player3;
    }

    public void setPlayer3(Arqueiro player3) {
        this.player3 = player3;
        txtnome.setText(player3.getNome());
        txtraca.setText(player3.getRaca());
        txtclasse.setText(player3.getClasse());
        txtidade.setText(Integer.toString(player3.getIdade()));
        txtsexo.setText(player3.getSexo());
        txtforca.setText(Integer.toString(player3.getForca()));
        txtdestreza.setText(Integer.toString(player3.getDestreza()));
        txtconstituicao.setText(Integer.toString(player3.getConstituicao()));
        txtinteligencia.setText(Integer.toString(player3.getInteligencia()));
        txtsabedoria.setText(Integer.toString(player3.getSabedoria()));
        txtcarisma.setText(Integer.toString(player3.getCarisma()));
        txtdeslocamento.setText(Integer.toString(player3.getDeslocamento()));
        txtnivel.setText(Integer.toString(player3.getNivel()));
        txtxp.setText(Integer.toString(player3.getXp())+"/" + Integer.toString(player3.getNivel()*300));
        txthp.setText(Integer.toString(player3.getHpAtual())+"/" + Integer.toString(player3.getHp()));
    
if("M".equals(player3.getSexo())){
          if("Anão".equals(player3.getRaca())){
                  ImageIcon img = new ImageIcon(this.getClass().getResource("/projetofinalpoo/dwarf-M-arqueiro.jpg"));
                  IMAGE.setIcon(img);
          }else if("Elfo".equals(player3.getRaca())){
                  ImageIcon img = new ImageIcon(this.getClass().getResource("/projetofinalpoo/elf-M-arqueiro.jpg"));
                  IMAGE.setIcon(img); 
          }else if("Humano".equals(player3.getRaca())){
              ImageIcon img = new ImageIcon(this.getClass().getResource("/projetofinalpoo/human-M-arqueiro.jpg"));
                  IMAGE.setIcon(img);
          }else if("Orc".equals(player3.getRaca())){
              ImageIcon img = new ImageIcon(this.getClass().getResource("/projetofinalpoo/orc-M-arqueiro.jpg"));
                  IMAGE.setIcon(img);
          }else if("Tiefling".equals(player3.getRaca())){
                   ImageIcon img = new ImageIcon(this.getClass().getResource("/projetofinalpoo/tiefling-M-arqueiro.jpg"));
                  IMAGE.setIcon(img);
            }
        
        }else{
         if("Anão".equals(player3.getRaca())){
                  ImageIcon img = new ImageIcon(this.getClass().getResource("/projetofinalpoo/dwarf-F-arqueiro.jpg"));
                  IMAGE.setIcon(img);
          }else if("Elfo".equals(player3.getRaca())){
                  ImageIcon img = new ImageIcon(this.getClass().getResource("/projetofinalpoo/elf-F-arqueiro.jpg"));
                  IMAGE.setIcon(img); 
          }else if("Humano".equals(player3.getRaca())){
              ImageIcon img = new ImageIcon(this.getClass().getResource("/projetofinalpoo/human-F-arqueiro.jpg"));
                  IMAGE.setIcon(img);
          }else if("Orc".equals(player3.getRaca())){
              ImageIcon img = new ImageIcon(this.getClass().getResource("/projetofinalpoo/orc-F-arqueiro.jpg"));
                  IMAGE.setIcon(img);
          }else if("Tiefling".equals(player3.getRaca())){
                   ImageIcon img = new ImageIcon(this.getClass().getResource("/projetofinalpoo/tiefling-F-arqueiro.jpg"));
                  IMAGE.setIcon(img);
            }
        }
    }

    public int getX() {
        return x;
    }

    public void setX(int x) {
        this.x = x;
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IMAGE;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtcarisma;
    private javax.swing.JTextField txtclasse;
    private javax.swing.JTextField txtconstituicao;
    private javax.swing.JTextField txtdeslocamento;
    private javax.swing.JTextField txtdestreza;
    private javax.swing.JTextField txtforca;
    private javax.swing.JTextField txthp;
    private javax.swing.JTextField txtidade;
    private javax.swing.JTextField txtinteligencia;
    private javax.swing.JTextField txtnivel;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtraca;
    private javax.swing.JTextField txtsabedoria;
    private javax.swing.JTextField txtsexo;
    private javax.swing.JTextField txtxp;
    // End of variables declaration//GEN-END:variables
}
